#!/usr/bin/env bash

run() {
  setsid swaymsg -t command exec "$1"
}

menu=(
  browser
  chromium
  emacs
  zathura
  gimp
  obs
  terminal
  files
  sv_se
  en_us
  squeak
  glam
  cursor
)

CHOICE=$(
  for c in "${menu[@]}"; do printf "%s\n" $c; done |
    sort -ur |
    fzf --reverse --no-info --no-scrollbar --prompt=' ' --pointer=' ' --border=none
)

if [[ "$CHOICE" != "" ]]; then
  case "$CHOICE" in
  "cursor")
    run "$HOME/opt/cursor"
    ;;
  "glam")
    run "$HOME/opt/glamorous-toolkit/bin/GlamorousToolkit"
    ;;
  "squeak")
    run "$HOME/opt/squeak/squeak.sh"
    ;;
  "emacs")
    run "emacs"
    ;;
  "terminal")
    run "foot"
    ;;
  "sv_se")
    swaymsg input type:keyboard xkb_layout "se"
    ;;
  "en_us")
    swaymsg input type:keyboard xkb_layout "us"
    ;;
  "files")
    run "thunar"
    ;;
  "browser")
    run "librewolf"
    ;;
  *)
    run "$CHOICE"
    ;;
  esac
fi
