# -*- conf -*-

font=JetBrains Mono:size=15
font-bold=JetBrains Mono:size=15

pad=10x10

[cursor]
style=block
color=ffffff 595959

[colors]
foreground=2c2e5d # Text
background=fbfbfb # Base

regular0=5c5f77   # Subtext 1
regular1=c20f39   # red
regular2=0c681c   # green
regular3=9f6e1d   # yellow
regular4=163d9c   # blue
regular5=ea76cb   # pink
regular6=05696a   # teal
regular7=acb0be   # Surface 2
bright0=6c6f85    # Subtext 0
bright1=d20f39    # red
bright2=40a02b    # green
bright3=9f6e1d    # yellow
bright4=1e66f5    # blue
bright5=ea76cb    # pink
bright6=179299    # teal
bright7=bcc0cc    # Surface 1
